POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhcmlAMTIzIiwiaWQiOjIsImlhdCI6MTY2MjYyNzg0Mn0.ch5BslXxI_NNdryZhB7w5S4_MFdYENsdrSAZr7pC4Hc

{
    "content": "new note by Hari.",
    "important": true
}

###
GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/users/
Content-Type: application/json; charset=utf-8


{
    "username":"hari@123",
    "name":"Hari"
}


###
POST http://localhost:3001/api/login/
Content-Type: application/json; charset=utf-8

{
"username": "hari@123",
"password":"secret"
}
