POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhcmliYWhhZHVyIiwiaWQiOjEsImlhdCI6MTY2MjcxNzE0Mn0.nu2Peja7zqb2YqawIUGzU7im5KK9MfkNQBU-cZjX0n0

{
    "content": "new note",
    "important": true
}

###
GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/users/
Content-Type: application/json; charset=utf-8


{
    "username":"sujanc",
    "name":"sujan"
}


###
POST http://localhost:3001/api/login/
Content-Type: application/json; charset=utf-8

{
"username": "haribahadur",
"password":"secret"
}

###
PUT http://localhost:3001/api/users/madanbahadur
Content-Type: application/json; charset=utf-8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhcmliYWhhZHVyIiwiaWQiOjEsImlhdCI6MTY2MjcxOTkzMX0.nzxHVkCHGKk6RFBWhaLpE4m1-1M0rglUpI4vnIFzNDE

{
    "disabled":false
}
